'use strict';
(function(){
 const KEY='steelstorm_housing_v2';
 const types=[{id:'hut',icon:'🛖',name:'Small Hut',cost:120,cap:2,req:0},{id:'house',icon:'🏠',name:'Basic House',cost:300,cap:5,req:0},{id:'family',icon:'🏘️',name:'Family House',cost:650,cap:10,req:0},{id:'apartment',icon:'🏢',name:'Apartment Block',cost:1800,cap:30,req:2},{id:'tower',icon:'🏙️',name:'High-Rise Tower',cost:6500,cap:100,req:5},{id:'luxury',icon:'🏰',name:'Luxury Residence',cost:3500,cap:12,req:1},{id:'mega',icon:'🌆',name:'Mega Tower',cost:20000,cap:300,req:10}];
 const state=JSON.parse(localStorage.getItem(KEY)||'null')||{houses:{hut:0,house:0,family:0,apartment:0,tower:0,luxury:0,mega:0},population:0};
 const $=id=>document.getElementById(id);function save(){localStorage.setItem(KEY,JSON.stringify(state))}function total(){return Object.values(state.houses).reduce((a,b)=>a+b,0)}function capacity(){return types.reduce((n,t)=>n+(state.houses[t.id]||0)*t.cap,0)}
 function render(){const box=$('housingPanel');if(!box)return;state.population=Math.min(state.population,capacity());box.innerHTML=`<div class="card"><h2>🏠 HOUSING & POPULATION</h2><p>Population: <b>${state.population}</b> / ${capacity()}</p><p class="muted">Housing is required to support your workforce.</p><div class="grid">${types.map(t=>{const owned=state.houses[t.id]||0,locked=t.req>total();return `<div class="card"><h3>${t.icon} ${t.name}</h3><p>Capacity: <b>${t.cap}</b> residents</p><p>Owned: <b>${owned}</b></p><p>Cost: <b>$${t.cost.toLocaleString()}</b></p>${locked?`<p class="muted">Requires ${t.req} other houses</p>`:`<button class="btn primary" data-house="${t.id}">BUY / BUILD</button>`}</div>`}).join('')}</div></div>`;box.querySelectorAll('[data-house]').forEach(b=>b.onclick=()=>buy(b.dataset.house))}
 function buy(id){const t=types.find(x=>x.id===id),e=window.steelstormEconomy;if(!e||e.money<t.cost)return alert('Not enough money for this house.');e.money-=t.cost;state.houses[id]++;state.population+=t.cap;save();localStorage.setItem('steelstorm_economy_v1',JSON.stringify(e));render();const mt=$('moneyTop');if(mt)mt.textContent=Math.floor(e.money).toLocaleString()}
 window.addEventListener('load',()=>{const b=$('buildings');if(b&&!$('housingPanel')){const d=document.createElement('div');d.id='housingPanel';b.prepend(d)}render()});
})();
