'use strict';
(function(){
  const KEY='steelstorm-base-v1';
  const troopList=[['Rifleman',100,25,70,100],['Heavy Infantry',180,35,45,160],['Sniper',80,70,95,220],['Machine Gunner',130,40,75,190],['Medic',90,10,55,150],['Engineer',110,20,50,140],['Anti-Armor',100,55,65,210],['Commander',150,30,60,300],['Assault Trooper',120,38,78,170],['Shield Trooper',220,28,40,230],['Recon Scout',90,24,115,180],['Combat Engineer',125,30,60,210],['Field Medic',110,12,68,240],['Mortar Team',105,82,48,280],['Drone Operator',100,35,105,320],['Heavy Gunner',210,58,42,330],['Elite Ranger',160,62,100,420],['Urban Assault',175,55,72,390],['Arctic Trooper',145,48,76,360],['Desert Trooper',145,48,76,360],['Paratrooper',130,52,92,410],['Shock Trooper',190,70,65,480],['Exo-Soldier',300,95,50,750],['Plasma Guard',240,110,85,900],['Cyber Commando',210,100,125,1100],['Titan Guard',420,135,38,1400],['Storm Legionnaire',360,150,105,1700]];
  const vehicleList=[['Scout-1','Light Tank',180,35,85,250],['Ironclad','Medium Tank',420,90,55,600],['Thunder-6','Medium Tank',440,105,50,650],['Titan','Heavy Tank',700,150,32,1000],['Falcon-X','Fighter Jet',300,100,140,900],['Raptor-Z','Fighter Jet',300,115,155,1050],['Titan Bomber','Heavy Jet',650,180,70,1800],['Sky Medic','Support Aircraft',260,20,105,800],['Storm Tank','Futuristic Tank',650,180,45,1700],['Void Tank','Futuristic Tank',700,190,40,1900],['Titan-X','Futuristic Tank',850,240,35,2400],['Apocalypse Tank','Futuristic Tank',1000,280,25,3000]];
  const buildingList=[['Construction Yard','Command',250,1],['Barracks','Military',300,3],['Vehicle Factory','Military',650,5],['Airfield','Military',800,6],['Fortress','Defense',700,5],['Supply Depot','Logistics',400,3],['Power Plant','Industry',500,4],['Weapons Research Lab','Research',900,7],['Vehicle Research Lab','Research',1000,8],['Aviation Research Lab','Research',1100,9],['Logistics Research Lab','Research',850,7],['Defense Research Lab','Research',900,7],['Science Institute','Research',1400,12]];
  function get(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{credits:1000,built:{},levels:{},mapObjects:[],units:[],vehiclesOwned:[]}}catch(e){return {credits:1000,built:{},levels:{},mapObjects:[],units:[],vehiclesOwned:[]}}}
  function put(s){localStorage.setItem(KEY,JSON.stringify(s));syncMoney();}
  function syncMoney(){document.querySelectorAll('#moneyTop').forEach(e=>e.textContent=Math.floor(get().credits||0).toLocaleString())}
  function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
  function add(s,type,name,x=70,y=69){const o={id:Date.now().toString(36)+Math.random().toString(36).slice(2),type,name,x,y};s.mapObjects=s.mapObjects||[];s.mapObjects.push(o);return o}
  function ensureLayer(){const map=document.getElementById('earthMap');if(!map)return null;let layer=document.getElementById('playerMapLayer');if(!layer){layer=document.createElement('div');layer.id='playerMapLayer';layer.style.cssText='position:absolute;inset:0;z-index:10;pointer-events:none';map.appendChild(layer)}return layer}
  function icon(type){return type==='troop'?'🪖':type==='building'?'🏭':type==='lab'?'🧪':type==='vehicle'?'🚙':'🛡️'}
  function renderMap(){const layer=ensureLayer();if(!layer)return;const s=get();layer.innerHTML=(s.mapObjects||[]).map(o=>`<button class="mapMarker dynamicPlayerMarker ${o.type==='troop'?'troop':o.type==='vehicle'?'player':o.type==='lab'?'building':o.type==='building'?'building':'defence'}" data-map-id="${o.id}" style="left:${Math.max(1,Math.min(99,o.x))}%;top:${Math.max(7,Math.min(96,o.y))}%;pointer-events:auto" title="Drag to move ${esc(o.name)}"><span style="font-size:24px">${icon(o.type)}</span><b>${esc(o.name)}</b></button>`).join('');layer.querySelectorAll('.dynamicPlayerMarker').forEach(el=>el.addEventListener('pointerdown',dragStart));}
  let drag=null;
  function dragStart(e){if(e.button!==undefined&&e.button!==0)return;const map=document.getElementById('earthMap');const id=e.currentTarget.dataset.mapId;if(!map)return;drag={id,map,el:e.currentTarget,moved:false};e.currentTarget.setPointerCapture?.(e.pointerId);window.addEventListener('pointermove',dragMove);window.addEventListener('pointerup',dragEnd,{once:true});e.preventDefault();e.stopPropagation()}
  function dragMove(e){if(!drag)return;const r=drag.map.getBoundingClientRect(),s=get(),o=(s.mapObjects||[]).find(x=>x.id===drag.id);if(!o)return;o.x=Math.max(1,Math.min(99,(e.clientX-r.left)/r.width*100));o.y=Math.max(7,Math.min(96,(e.clientY-r.top)/r.height*100));drag.el.style.left=o.x+'%';drag.el.style.top=o.y+'%';drag.moved=true}
  function dragEnd(){if(drag?.moved){const s=get(),o=(s.mapObjects||[]).find(x=>x.id===drag.id);put(s);notice(o?o.name+' moved. New position saved.':'Position saved.')}window.removeEventListener('pointermove',dragMove);drag=null}
  function notice(text){let n=document.getElementById('mapPurchaseNotice');if(!n){n=document.createElement('div');n.className='notice';n.id='mapPurchaseNotice';const m=document.getElementById('earthMap');if(m)m.parentNode.insertBefore(n,m.nextSibling)}n.textContent=text}
  function buyTroop(i){const t=troopList[i],s=get();if(!s.built?.Barracks)return alert('Buy and build the Barracks first.');if((s.credits||0)<t[4])return alert('Not enough funds.');s.credits-=t[4];const o=add(s,'troop',t[0],69+Math.random()*2,68+Math.random()*2);s.units=s.units||[];s.units.push({id:o.id,type:'troop',name:t[0]});put(s);renderMap();notice('Bought '+t[0]+'. Drag its 🪖 marker on the map to move it.');}
  function buyVehicle(i){const v=vehicleList[i],s=get(),req=v[1].includes('Jet')||v[1].includes('Aircraft')?'Airfield':'Vehicle Factory';if(!s.built?.[req])return alert('Buy and build the '+req+' first.');if((s.credits||0)<v[5])return alert('Not enough funds.');s.credits-=v[5];const o=add(s,'vehicle',v[0],68+Math.random()*3,67+Math.random()*3);s.vehiclesOwned=s.vehiclesOwned||[];s.vehiclesOwned.push(v[0]);put(s);renderMap();notice('Bought '+v[0]+'. Drag its 🚙 marker on the map to move it.');}
  function buyBuilding(i){const b=buildingList[i],s=get();if(s.built?.[b[0]])return alert('That building is already built.');if(b[0]!=='Construction Yard'&&!s.built?.['Construction Yard'])return alert('Buy and build the Construction Yard first.');if((s.credits||0)<b[2])return alert('Not enough funds.');s.credits-=b[2];s.built=s.built||{};s.levels=s.levels||{};s.built[b[0]]=true;s.levels[b[0]]=1;const isLab=b[0].includes('Lab')||b[0]==='Science Institute';add(s,isLab?'lab':'building',b[0],69+Math.random()*2,68+Math.random()*2);put(s);renderMap();notice('Bought '+b[0]+'. Drag the building marker to reposition it.');renderBuildingCards();}
  function renderBuildingCards(){const el=document.getElementById('buildingCards');if(!el)return;const s=get();el.innerHTML=buildingList.map((b,i)=>{const built=!!s.built?.[b[0]];return `<div class="card"><span class="tag">${esc(b[1])}</span><h2>${esc(b[0])}</h2><div class="stat"><span>Status</span><b>${built?'BUILT LV 1':'NOT BUILT'}</b></div><div class="stat"><span>Price</span><b>$${b[2]}</b></div><button class="btn" ${built?'disabled':''} onclick="window.steelstormMap.buyBuilding(${i})">${built?'BUILT':'BUY & BUILD'}</button></div>`}).join('')}
  function renderTroopCards(){const el=document.getElementById('troopCards');if(!el)return;const s=get();el.innerHTML=troopList.map((t,i)=>`<div class="card"><span class="tag">INFANTRY</span><h2>${esc(t[0])}</h2><p>Visible map unit</p><div class="stat"><span>HP</span><b>${t[1]}</b></div><div class="stat"><span>Damage</span><b>${t[2]}</b></div><div class="stat"><span>Cost</span><b>$${t[4]}</b></div><button class="btn" ${s.built?.Barracks?'':'disabled'} onclick="window.steelstormMap.buyTroop(${i})">${s.built?.Barracks?'BUY & STATION':'BUILD BARRACKS FIRST'}</button></div>`).join('')}
  function renderVehicleCards(){const el=document.getElementById('vehicleCards');if(!el)return;const s=get();el.innerHTML=vehicleList.map((v,i)=>{const req=v[1].includes('Jet')||v[1].includes('Aircraft')?'Airfield':'Vehicle Factory',ok=!!s.built?.[req];return `<div class="card"><span class="tag">${esc(v[1])}</span><h2>${esc(v[0])}</h2><div class="stat"><span>HP</span><b>${v[2]}</b></div><div class="stat"><span>Cost</span><b>$${v[5]}</b></div><button class="btn" ${ok?'':'disabled'} onclick="window.steelstormMap.buyVehicle(${i})">${ok?'BUY & DEPLOY':'BUILD '+req.toUpperCase()}</button></div>`}).join('')}
  function controls(){const map=document.getElementById('earthMap');if(!map||document.getElementById('mapPurchaseControls'))return;const box=document.createElement('div');box.id='mapPurchaseControls';box.className='card';box.style.cssText='position:absolute;left:14px;bottom:38px;z-index:12;width:min(360px,calc(100% - 28px));background:rgba(5,12,19,.92);padding:10px';box.innerHTML='<b>LIVE MAP CONTROLS</b><div class="muted" style="margin:5px 0 8px">Buy items, then drag their full markers around the map.</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:6px"><button class="btn" id="quickTroop">🪖 TROOP</button><button class="btn" id="quickBuilding">🏭 BUILDING</button><button class="btn" id="quickVehicle">🚙 VEHICLE</button></div>';map.appendChild(box);box.querySelector('#quickTroop').onclick=()=>show('troops');box.querySelector('#quickBuilding').onclick=()=>show('buildings');box.querySelector('#quickVehicle').onclick=()=>show('vehicles')}
  function show(id){if(typeof window.show==='function')window.show(id);else document.querySelector(`[data-go="${id}"]`)?.click()}
  window.steelstormMap={buyTroop:buyTroop,buyBuilding:buyBuilding,buyVehicle:buyVehicle,render:renderMap};
  function boot(){controls();renderMap();syncMoney();}
  document.addEventListener('click',e=>{const n=e.target.closest('[data-go]');if(n&&n.dataset.go==='world')setTimeout(boot,30);if(n&&n.dataset.go==='dashboard')setTimeout(boot,30);if(n&&n.dataset.go==='troops')setTimeout(renderTroopCards,30);if(n&&n.dataset.go==='vehicles')setTimeout(renderVehicleCards,30);if(n&&n.dataset.go==='buildings')setTimeout(renderBuildingCards,30)});
  window.addEventListener('load',()=>{setTimeout(boot,50);setTimeout(()=>{renderTroopCards();renderVehicleCards();renderBuildingCards()},80)});
  setInterval(()=>{renderMap();syncMoney()},3000);
})();
