'use strict';
(function(){
  const state={peer:null,room:'',host:false,connections:new Map(),selfId:'',name:'Commander'};
  const $=id=>document.getElementById(id);
  function uiStatus(t){const e=$('mpStatus');if(e)e.textContent=t}
  function log(t){const e=$('mpChat');if(!e)return;e.textContent+=(e.textContent?'\n':'')+t;e.scrollTop=e.scrollHeight}
  function name(){return (($('mpName')?.value||'Commander').trim().slice(0,18))||'Commander'}
  function code(){return (($('mpRoom')?.value||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'')).slice(0,6)}
  function players(list){const e=$('mpPlayers');if(!e)return;e.innerHTML=list.length?list.map(p=>'<div class="playerRow"><span><i class="onlineDot"></i>'+escapeHtml(p.name)+'</span><span class="muted">'+(p.host?'HOST':'ONLINE')+'</span></div>').join(''):'<div class="muted">No players connected.</div>'}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function roomCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
  function wire(c,isHost){c.on('open',()=>{state.connections.set(c.peer,c);uiStatus('Connected. Room '+state.room);if(isHost)broadcast({type:'roster',players:roster()});else c.send({type:'hello',name:state.name});renderRoster()});c.on('data',m=>onMessage(c,m));c.on('close',()=>{state.connections.delete(c.peer);renderRoster();if(state.host)broadcast({type:'roster',players:roster()})});c.on('error',e=>{log('Connection error: '+(e?.message||'unknown'));state.connections.delete(c.peer);renderRoster()})}
  function roster(){const a=[{id:state.selfId,name:state.name,host:state.host}];state.connections.forEach((c,id)=>a.push({id,name:c.__name||'Commander',host:false}));return a}
  function renderRoster(){players(roster())}
  function broadcast(m,except){state.connections.forEach((c,id)=>{if(id!==except&&c.open)try{c.send(m)}catch(e){}})}
  function onMessage(c,m){if(!m||typeof m!=='object')return;if(m.type==='hello'&&state.host){c.__name=(m.name||'Commander').slice(0,18);c.send({type:'welcome',name:state.name,room:state.room,players:roster(),world:getWorld()});broadcast({type:'roster',players:roster()});renderRoster();return}if(m.type==='welcome'){uiStatus('Connected to '+(m.name||'host')+' • Room '+state.room);if(Array.isArray(m.players))players(m.players);if(m.world)applyRemoteWorld(m.world);return}if(m.type==='roster'){if(Array.isArray(m.players))players(m.players);return}if(m.type==='chat'){log(m.name+': '+m.text);return}if(m.type==='worldState'){applyRemoteWorld(m.data);return}}
  function create(){if(!window.Peer)return uiStatus('Multiplayer library failed to load. Refresh the page.');if(state.peer)return;state.name=name();state.room=roomCode();state.host=true;state.selfId='ss-'+state.room;uiStatus('Creating room '+state.room+'…');try{state.peer=new Peer(state.selfId);state.peer.on('open',id=>{state.selfId=id;uiStatus('ROOM '+state.room+' CREATED. Send this code to your friend.');$('mpCopy').disabled=false;$('mpLeave').disabled=false;renderRoster()});state.peer.on('connection',c=>wire(c,true));state.peer.on('error',e=>uiStatus('Room error: '+(e?.type||e?.message||'unknown')))}catch(e){uiStatus('Could not create room. Try again.');state.peer=null}}
  function join(){if(!window.Peer)return uiStatus('Multiplayer library failed to load. Refresh the page.');if(state.peer)return;const r=code();if(r.length!==6)return uiStatus('Enter a 6-character room code.');state.name=name();state.room=r;state.host=false;uiStatus('Joining room '+r+'…');try{state.peer=new Peer();state.peer.on('open',id=>{state.selfId=id;const c=state.peer.connect('ss-'+r,{reliable:true});wire(c,false);state.connections.set('ss-'+r,c)});state.peer.on('error',e=>uiStatus('Join failed: '+(e?.type||e?.message||'check the room code')))}catch(e){uiStatus('Could not join room. Try again.');state.peer=null}}
  function leave(){state.connections.forEach(c=>{try{c.close()}catch(e){}});state.connections.clear();if(state.peer){try{state.peer.destroy()}catch(e){}}state.peer=null;state.room='';state.host=false;state.selfId='';$('mpCopy').disabled=true;$('mpLeave').disabled=true;uiStatus('Offline. Create or join a room.');renderRoster()}
  function sendChat(){const i=$('mpChatInput'),t=(i?.value||'').trim();if(!t)return;if(!state.peer)return uiStatus('Join a room first.');const m={type:'chat',name:state.name,text:t.slice(0,120)};log('You: '+m.text);broadcast(m);i.value=''}
  async function copy(){if(!state.room)return;try{await navigator.clipboard.writeText(state.room);uiStatus('Room code '+state.room+' copied.')}catch(e){uiStatus('Room code: '+state.room)}}

  const regions=[['North America','🌎',14,25],['South America','🌎',34,62],['Europe','🌍',52,28],['Africa','🌍',51,55],['Asia','🌏',69,36],['Oceania','🌏',79,68],['Arctic','❄️',52,10],['Antarctica','❄️',52,88]];
  const defaultEmpire={spawn:null,territory:{},exploring:[],economy:150,workers:5,army:0,power:0};
  let empire=loadEmpire();
  function loadEmpire(){try{return Object.assign({},defaultEmpire,JSON.parse(localStorage.getItem('steelstorm-empire-v1')||'null'))}catch{return Object.assign({},defaultEmpire)}}
  function saveEmpire(){localStorage.setItem('steelstorm-empire-v1',JSON.stringify(empire))}
  function getWorld(){return JSON.parse(JSON.stringify(empire))}
  function injectEmpireUI(){const world=$('world');if(!world||world.querySelector('.empirePanel'))return;const style=document.createElement('style');style.textContent='.empirePanel{margin-bottom:16px}.spawnMap{position:relative;min-height:430px;border:1px solid #42586c;border-radius:12px;overflow:hidden;background:#07131d}.spawnBg{position:absolute;inset:0;background:url("https://upload.wikimedia.org/wikipedia/commons/1/1d/PAT_-_World_satellite_with_borders.jpg") center/cover;filter:saturate(1.08) brightness(.68)}.spawnShade{position:absolute;inset:0;background:rgba(2,8,14,.3)}.spawnBtn{position:absolute;transform:translate(-50%,-50%);padding:8px;border:1px solid #a9d5ff;border-radius:8px;background:rgba(5,14,23,.9);color:white;font-weight:800;cursor:pointer}.spawnBtn.selected{outline:3px solid white;background:#275276}.empStats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.empStat{padding:12px;background:#0d151e;border:1px solid #2c3947;border-radius:8px}.empStat b{display:block;font-size:25px;margin-top:3px}.empActions{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.exploreLine{display:flex;justify-content:space-between;padding:8px;border-bottom:1px solid #263442}@media(max-width:700px){.empStats,.empActions{grid-template-columns:1fr}.spawnMap{min-height:340px}}';document.head.appendChild(style);const p=document.createElement('div');p.className='card empirePanel';p.innerHTML='<h2>🌐 EMPIRE EXPANSION</h2><div id="spawnStatus" class="notice"></div><div id="spawnMap" class="spawnMap"><div class="spawnBg"></div><div class="spawnShade"></div></div><div id="empStats" class="empStats"></div><div class="empActions"><div class="card"><h3>🧭 Explore</h3><p class="muted">Send scouts to discover new land. Expeditions take time.</p><button class="btn primary" id="sendExplorer">SEND EXPLORER</button><div id="exploreList"></div></div><div class="card"><h3>🏭 Economy</h3><p class="muted">Develop farms, industry and housing as your territory grows.</p><button class="btn" id="buildEconomy">BUILD INDUSTRY</button><button class="btn" id="buildHousing" style="margin-top:7px">BUILD HOUSING</button></div><div class="card"><h3>♜ Army</h3><p class="muted">Turn workers and economic power into soldiers.</p><button class="btn" id="raiseArmy">RECRUIT 10 SOLDIERS</button></div></div><div class="notice"><b>CONQUEST:</b> Pick a starting point, secure a small homeland, explore outward, build your economy, raise an army, and eventually fight rivals for control of the world.</div>';world.insertBefore(p,world.firstChild);$('sendExplorer').onclick=sendExplorer;$('buildEconomy').onclick=buildEconomy;$('buildHousing').onclick=buildHousing;$('raiseArmy').onclick=raiseArmy;renderEmpire()}
  function renderEmpire(){const map=$('spawnMap');if(!map)return;map.querySelectorAll('.spawnBtn').forEach(x=>x.remove());const status=$('spawnStatus');status.textContent=empire.spawn===null?'Choose your spawn point. You will begin with only this small region.':'Spawn: '+regions[empire.spawn][0]+' • Controlled regions: '+Object.keys(empire.territory).length;regions.forEach((r,i)=>{const b=document.createElement('button');b.className='spawnBtn '+(empire.spawn===i?'selected':'');b.style.left=r[2]+'%';b.style.top=r[3]+'%';b.textContent=r[1]+' '+r[0];b.onclick=()=>chooseSpawn(i);map.appendChild(b)});$('empStats').innerHTML='<div class="empStat">LAND<b>'+Object.keys(empire.territory).length+'</b></div><div class="empStat">ECONOMY<b>$'+empire.economy+'</b></div><div class="empStat">WORKERS<b>'+empire.workers+'</b></div><div class="empStat">SOLDIERS<b>'+empire.army+'</b></div>';$('exploreList').innerHTML=empire.exploring.length?empire.exploring.map(x=>'<div class="exploreLine"><span>🧭 '+regions[x.region][0]+'</span><b>'+x.turns+' turns</b></div>').join(''):'<p class="muted">No active expeditions.</p>'}
  function chooseSpawn(i){if(empire.spawn!==null)return alert('Spawn is locked. Reset the empire save to choose another.');empire.spawn=i;empire.territory={[i]:true};saveEmpire();renderEmpire();broadcastWorld()}
  function sendExplorer(){if(empire.spawn===null)return alert('Choose a spawn point first.');if(empire.economy<40)return alert('Need 40 economy funds.');const candidates=regions.map((_,i)=>i).filter(i=>!empire.territory[i]&&!empire.exploring.some(x=>x.region===i));if(!candidates.length)return alert('All available regions have been explored.');const r=candidates[Math.floor(Math.random()*candidates.length)];empire.economy-=40;empire.exploring.push({region:r,turns:3});saveEmpire();renderEmpire();broadcastWorld()}
  function tickExploration(){if(empire.spawn===null)return;let done=false;empire.exploring.forEach(x=>x.turns--);empire.exploring.filter(x=>x.turns<=0).forEach(x=>{empire.territory[x.region]=true;empire.economy+=75;empire.workers+=5;done=true});empire.exploring=empire.exploring.filter(x=>x.turns>0);if(done){saveEmpire();renderEmpire();broadcastWorld()}else{saveEmpire();renderEmpire()}}
  function buildEconomy(){if(empire.spawn===null)return alert('Choose a spawn point first.');if(empire.economy<75)return alert('Need 75 economy funds.');empire.economy-=75;empire.economy+=110;empire.workers+=2;saveEmpire();renderEmpire();broadcastWorld()}
  function buildHousing(){if(empire.economy<50)return alert('Need 50 economy funds.');empire.economy-=50;empire.workers+=5;saveEmpire();renderEmpire();broadcastWorld()}
  function raiseArmy(){if(empire.economy<60)return alert('Need 60 economy funds.');if(empire.workers<2)return alert('Need at least 2 workers.');empire.economy-=60;empire.workers-=2;empire.army+=10;empire.power+=10;saveEmpire();renderEmpire();broadcastWorld()}
  function broadcastWorld(){if(state.peer&&state.host)broadcast({type:'worldState',data:getWorld()})}
  function applyRemoteWorld(d){window.remoteEmpires=window.remoteEmpires||[];window.remoteEmpires.push(d);const l=$('battleLog');if(l)l.textContent='Another commander has '+Object.keys(d.territory||{}).length+' regions, '+(d.army||0)+' soldiers and $'+(d.economy||0)+' economy.'}
  function init(){ $('mpHost')?.addEventListener('click',create);$('mpJoin')?.addEventListener('click',join);$('mpLeave')?.addEventListener('click',leave);$('mpCopy')?.addEventListener('click',copy);$('mpSend')?.addEventListener('click',sendChat);$('mpChatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()});players([]);injectEmpireUI() }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  setInterval(tickExploration,10000);
})();
